{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "syncthing.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.config.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
  {{- with .Values.persistence.config.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
