apiVersion: v2
name: speedtest-tracker
description: A Helm chart for deploying Speedtest Tracker on Kubernetes
type: application
version: 0.1.0
appVersion: "1.14.0"
home: https://github.com/alexjustesen/speedtest-tracker
sources:
  - https://github.com/alexjustesen/speedtest-tracker
keywords:
  - speedtest
  - tracker
  - network
  - monitoring
maintainers:
  - name: harish2k01
