apiVersion: v2
name: umami
description: A Helm chart for Umami, a privacy-focused web analytics platform
type: application
icon: https://raw.githubusercontent.com/selfhst/icons/main/png/umami.png
version: 0.1.0
appVersion: "3.1.0"
keywords:
  - analytics
  - privacy
  - web-analytics
  - umami
home: https://umami.is
sources:
  - https://github.com/umami-software/umami
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/images: |
    - name: umami
      image: ghcr.io/umami-software/umami:3.1.0
    - name: postgresql
      image: postgres:17-alpine
maintainers:
  - name: harish2k01
