apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scrutiny.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    web:
      listen:
        port: 8080

    database:
      location: /opt/scrutiny/config/scrutiny.db

    devices:
      - host: 10.10.10.104
        port: 22
        user: truenas_admin
        identity_file: /opt/scrutiny/ssh/id_ed25519