apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scrutiny.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scrutiny.labels" . | nindent 4 }}
data:
  scrutiny.yaml: |
    version: 1
    web:
      listen:
        host: 0.0.0.0
        port: 8080
        basepath: {{ .Values.scrutiny.web.basepath | quote }}
      database:
        location: {{ .Values.scrutiny.web.database.location | quote }}
      src:
        frontend:
          path: /opt/scrutiny/web
      influxdb:
        scheme: {{ .Values.scrutiny.web.influxdb.scheme | quote }}
        host: {{ .Values.scrutiny.web.influxdb.host | quote }}
        port: {{ .Values.scrutiny.web.influxdb.port }}
        retention_policy: {{ .Values.scrutiny.web.influxdb.retentionPolicy }}
    log:
      file: {{ .Values.scrutiny.log.file | quote }}
      level: {{ .Values.scrutiny.log.level | quote }}
{{- with .Values.scrutiny.notify.urls }}
    notify:
      urls:
{{ toYaml . | indent 8 }}
{{- end }}
