{{- $fullName := include "adguard-home.fullname" . -}}
{{- $sharedPersistence := and .Values.persistence.shared.enabled (or .Values.persistence.work.enabled .Values.persistence.conf.enabled) -}}
{{- if and $sharedPersistence (not .Values.persistence.shared.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.shared.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.shared.size }}
  {{- with .Values.persistence.shared.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
---
{{- end }}
{{- if and (not $sharedPersistence) .Values.persistence.work.enabled (not .Values.persistence.work.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-work
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.work.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.work.size }}
  {{- with .Values.persistence.work.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
---
{{- end }}
{{- if and (not $sharedPersistence) .Values.persistence.conf.enabled (not .Values.persistence.conf.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-conf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.conf.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.conf.size }}
  {{- with .Values.persistence.conf.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
