{{- if and .Values.database.mariadb.enabled (not .Values.database.mariadb.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uptime-kuma.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  {{ .Values.database.mariadb.auth.passwordKey }}: {{ required "database.mariadb.auth.password or database.mariadb.auth.existingSecret is required" .Values.database.mariadb.auth.password | b64enc | quote }}
  {{- if .Values.database.mariadb.auth.rootPassword }}
  {{ default "db-root-password" .Values.database.mariadb.auth.rootPasswordKey }}: {{ .Values.database.mariadb.auth.rootPassword | b64enc | quote }}
  {{- end }}
{{- end }}
