apiVersion: v2
name: flaresolverr
description: Deploys FlareSolverr on Kubernetes
type: application
icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/flaresolverr.png
version: 0.1.0
appVersion: "v3.4.6"
home: https://github.com/FlareSolverr/FlareSolverr
sources:
  - https://github.com/FlareSolverr/FlareSolverr
keywords:
  - flaresolverr
  - cloudflare
  - prowlarr
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/images: |
    - name: flaresolverr
      image: ghcr.io/flaresolverr/flaresolverr:v3.4.6
maintainers:
  - name: harish2k01
