{{- if and .Values.database.postgresql.enabled (not .Values.database.postgresql.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portfolio-tracker.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portfolio-tracker.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  {{ .Values.database.postgresql.auth.passwordKey }}: {{ required "database.postgresql.auth.password or database.postgresql.auth.existingSecret is required" .Values.database.postgresql.auth.password | b64enc | quote }}
{{- end }}
