{{- if not .Values.portfolioTracker.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portfolio-tracker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portfolio-tracker.labels" . | nindent 4 }}
type: Opaque
data:
  NEXTAUTH_SECRET: {{ required "portfolioTracker.secrets.inline.NEXTAUTH_SECRET or portfolioTracker.secrets.existingSecret is required" .Values.portfolioTracker.secrets.inline.NEXTAUTH_SECRET | b64enc | quote }}
  {{- with .Values.portfolioTracker.secrets.inline.SMTP_USER }}
  SMTP_USER: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.portfolioTracker.secrets.inline.SMTP_PASS }}
  SMTP_PASS: {{ . | b64enc | quote }}
  {{- end }}
{{- end }}
