apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio-tracker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portfolio-tracker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "portfolio-tracker.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: application
