apiVersion: v2
name: firefly-iii
description: A Helm chart for deploying Firefly III with PostgreSQL
type: application
icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/firefly-iii.png
version: 0.1.0
appVersion: "version-6.6.1"
home: https://www.firefly-iii.org/
sources:
  - https://github.com/firefly-iii/firefly-iii
keywords:
  - firefly-iii
  - finance
  - budgeting
  - personal-finance
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/images: |
    - name: firefly-iii
      image: fireflyiii/core:version-6.6.1
    - name: postgresql
      image: postgres:16-alpine
    - name: curl
      image: curlimages/curl:8.19.0
maintainers:
  - name: harish2k01
