{{- if and .Values.authKey.create (not .Values.authKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tailscale.authSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tailscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.authKey.existingSecretKey }}: {{ required "authKey.value is required when authKey.create=true" .Values.authKey.value | quote }}
{{- end }}
