apiVersion: v2
name: qbittorrent
description: Deploys qBittorrent on Kubernetes
type: application
icon: https://raw.githubusercontent.com/selfhst/icons/main/png/qbittorrent.png
version: 0.1.2
appVersion: "5.2.0"
home: https://www.qbittorrent.org
sources:
  - https://github.com/qbittorrent/qBittorrent
  - https://docs.linuxserver.io/images/docker-qbittorrent/
keywords:
  - qbittorrent
  - torrent
  - media
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/images: |
    - name: qbittorrent
      image: lscr.io/linuxserver/qbittorrent:5.2.0
maintainers:
  - name: harish2k01
