apiVersion: v2
name: qbittorrent-exporter
description: Deploys the martabal qBittorrent Prometheus exporter on Kubernetes
type: application
icon: https://raw.githubusercontent.com/selfhst/icons/main/png/qbittorrent.png
version: 0.1.0
appVersion: "v2.0.1"
home: https://github.com/martabal/qbittorrent-exporter
sources:
  - https://github.com/martabal/qbittorrent-exporter
keywords:
  - qbittorrent
  - prometheus
  - exporter
  - monitoring
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/images: |
    - name: qbittorrent-exporter
      image: ghcr.io/martabal/qbittorrent-exporter:v2.0.1
maintainers:
  - name: harish2k01
