{{- if .Values.proxmox.config.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pve-exporter.configSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pve-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.proxmox.config.secretKey }}: |
    {{- required "proxmox.config.value is required when proxmox.config.createSecret=true" .Values.proxmox.config.value | nindent 4 }}
{{- end }}
