{{- if and .Values.database.external.enabled (not .Values.database.external.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "speedtest-tracker.fullname" . }}-db-external
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "speedtest-tracker.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  {{ .Values.database.external.passwordKey }}: {{ required "database.external.password or database.external.existingSecret is required" .Values.database.external.password | b64enc | quote }}
{{- end }}
