{{- $db := "" }}
{{- if .Values.database.mariadb.enabled }}
{{- $db = "mariadb" }}
{{- else if .Values.database.mysql.enabled }}
{{- $db = "mysql" }}
{{- else if .Values.database.postgresql.enabled }}
{{- $db = "postgresql" }}
{{- end }}
{{- if $db }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "speedtest-tracker.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "speedtest-tracker.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  serviceName: {{ include "speedtest-tracker.fullname" . }}-db
  replicas: 1
  selector:
    matchLabels:
      {{- include "speedtest-tracker.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        {{- include "speedtest-tracker.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: database
    spec:
      {{- if eq $db "mariadb" }}
      {{- with .Values.database.mariadb.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mariadb
          image: "{{ .Values.database.mariadb.image.repository }}:{{ .Values.database.mariadb.image.tag }}"
          imagePullPolicy: {{ .Values.database.mariadb.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: {{ .Values.database.mariadb.service.port }}
              protocol: TCP
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.database.mariadb.auth.database | quote }}
            - name: MYSQL_USER
              value: {{ .Values.database.mariadb.auth.username | quote }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-db" (include "speedtest-tracker.fullname" .)) .Values.database.mariadb.auth.existingSecret }}
                  key: {{ .Values.database.mariadb.auth.passwordKey }}
            {{- if .Values.database.mariadb.auth.rootPassword }}
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-db" (include "speedtest-tracker.fullname" .)) .Values.database.mariadb.auth.existingSecret }}
                  key: {{ default "db-root-password" .Values.database.mariadb.auth.rootPasswordKey }}
            {{- else }}
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "true"
            {{- end }}
          {{- if .Values.database.mariadb.healthcheck.enabled }}
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - healthcheck.sh --connect --innodb_initialized
            initialDelaySeconds: 60
            periodSeconds: {{ .Values.database.mariadb.healthcheck.interval | replace "s" "" | int }}
            timeoutSeconds: {{ .Values.database.mariadb.healthcheck.timeout | replace "s" "" | int }}
            failureThreshold: {{ .Values.database.mariadb.healthcheck.retries }}
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - healthcheck.sh --connect --innodb_initialized
            initialDelaySeconds: 10
            periodSeconds: {{ .Values.database.mariadb.healthcheck.interval | replace "s" "" | int }}
            timeoutSeconds: {{ .Values.database.mariadb.healthcheck.timeout | replace "s" "" | int }}
            failureThreshold: {{ .Values.database.mariadb.healthcheck.retries }}
          {{- end }}
          {{- with .Values.database.mariadb.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      {{- with .Values.database.mariadb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- else if eq $db "mysql" }}
      {{- with .Values.database.mysql.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mysql
          image: "{{ .Values.database.mysql.image.repository }}:{{ .Values.database.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.database.mysql.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: {{ .Values.database.mysql.service.port }}
              protocol: TCP
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.database.mysql.auth.database | quote }}
            - name: MYSQL_USER
              value: {{ .Values.database.mysql.auth.username | quote }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-db" (include "speedtest-tracker.fullname" .)) .Values.database.mysql.auth.existingSecret }}
                  key: {{ .Values.database.mysql.auth.passwordKey }}
            {{- if .Values.database.mysql.auth.rootPassword }}
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-db" (include "speedtest-tracker.fullname" .)) .Values.database.mysql.auth.existingSecret }}
                  key: {{ default "db-root-password" .Values.database.mysql.auth.rootPasswordKey }}
            {{- else }}
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "true"
            {{- end }}
          {{- if .Values.database.mysql.healthcheck.enabled }}
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - mysqladmin ping -h localhost -u {{ .Values.database.mysql.auth.username }} -p${MYSQL_PASSWORD}
            initialDelaySeconds: 60
            periodSeconds: {{ .Values.database.mysql.healthcheck.interval | replace "s" "" | int }}
            timeoutSeconds: {{ .Values.database.mysql.healthcheck.timeout | replace "s" "" | int }}
            failureThreshold: {{ .Values.database.mysql.healthcheck.retries }}
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - mysqladmin ping -h localhost -u {{ .Values.database.mysql.auth.username }} -p${MYSQL_PASSWORD}
            initialDelaySeconds: 10
            periodSeconds: {{ .Values.database.mysql.healthcheck.interval | replace "s" "" | int }}
            timeoutSeconds: {{ .Values.database.mysql.healthcheck.timeout | replace "s" "" | int }}
            failureThreshold: {{ .Values.database.mysql.healthcheck.retries }}
          {{- end }}
          {{- with .Values.database.mysql.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      {{- with .Values.database.mysql.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- else if eq $db "postgresql" }}
      {{- with .Values.database.postgresql.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: postgresql
          image: "{{ .Values.database.postgresql.image.repository }}:{{ .Values.database.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.database.postgresql.image.pullPolicy }}
          ports:
            - name: postgresql
              containerPort: {{ .Values.database.postgresql.service.port }}
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.postgresql.auth.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.database.postgresql.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-db" (include "speedtest-tracker.fullname" .)) .Values.database.postgresql.auth.existingSecret }}
                  key: {{ .Values.database.postgresql.auth.passwordKey }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          {{- if .Values.database.postgresql.healthcheck.enabled }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U {{ .Values.database.postgresql.auth.username }}
            initialDelaySeconds: 60
            periodSeconds: {{ .Values.database.postgresql.healthcheck.interval | replace "s" "" | int }}
            timeoutSeconds: {{ .Values.database.postgresql.healthcheck.timeout | replace "s" "" | int }}
            failureThreshold: {{ .Values.database.postgresql.healthcheck.retries }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U {{ .Values.database.postgresql.auth.username }}
            initialDelaySeconds: 10
            periodSeconds: {{ .Values.database.postgresql.healthcheck.interval | replace "s" "" | int }}
            timeoutSeconds: {{ .Values.database.postgresql.healthcheck.timeout | replace "s" "" | int }}
            failureThreshold: {{ .Values.database.postgresql.healthcheck.retries }}
          {{- end }}
          {{- with .Values.database.postgresql.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      {{- with .Values.database.postgresql.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if or (and (eq $db "mariadb") .Values.database.mariadb.persistence.existingClaim) (and (eq $db "mysql") .Values.database.mysql.persistence.existingClaim) (and (eq $db "postgresql") .Values.database.postgresql.persistence.existingClaim) }}
      volumes:
        - name: data
          persistentVolumeClaim:
            {{ if eq $db "mariadb" }}
            claimName: {{ .Values.database.mariadb.persistence.existingClaim }}
            {{ else if eq $db "mysql" }}
            claimName: {{ .Values.database.mysql.persistence.existingClaim }}
            {{ else if eq $db "postgresql" }}
            claimName: {{ .Values.database.postgresql.persistence.existingClaim }}
            {{ end }}
      {{- else if or (and (eq $db "mariadb") (not .Values.database.mariadb.persistence.enabled)) (and (eq $db "mysql") (not .Values.database.mysql.persistence.enabled)) (and (eq $db "postgresql") (not .Values.database.postgresql.persistence.enabled)) }}
      volumes:
        - name: data
          emptyDir: {}
      {{- end }}

  {{- if or (and (eq $db "mariadb") .Values.database.mariadb.persistence.enabled (not .Values.database.mariadb.persistence.existingClaim)) (and (eq $db "mysql") .Values.database.mysql.persistence.enabled (not .Values.database.mysql.persistence.existingClaim)) (and (eq $db "postgresql") .Values.database.postgresql.persistence.enabled (not .Values.database.postgresql.persistence.existingClaim)) }}
  volumeClaimTemplates:
    {{- if eq $db "mariadb" }}
    - metadata:
        name: data
        labels:
          {{- include "speedtest-tracker.labels" . | nindent 10 }}
      spec:
        accessModes:
          {{- toYaml .Values.database.mariadb.persistence.accessModes | nindent 10 }}
        {{- if .Values.database.mariadb.persistence.storageClassName }}
        storageClassName: {{ .Values.database.mariadb.persistence.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.database.mariadb.persistence.size }}
    {{- else if eq $db "mysql" }}
    - metadata:
        name: data
        labels:
          {{- include "speedtest-tracker.labels" . | nindent 10 }}
      spec:
        accessModes:
          {{- toYaml .Values.database.mysql.persistence.accessModes | nindent 10 }}
        {{- if .Values.database.mysql.persistence.storageClassName }}
        storageClassName: {{ .Values.database.mysql.persistence.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.database.mysql.persistence.size }}
    {{- else if eq $db "postgresql" }}
    - metadata:
        name: data
        labels:
          {{- include "speedtest-tracker.labels" . | nindent 10 }}
      spec:
        accessModes:
          {{- toYaml .Values.database.postgresql.persistence.accessModes | nindent 10 }}
        {{- if .Values.database.postgresql.persistence.storageClassName }}
        storageClassName: {{ .Values.database.postgresql.persistence.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.database.postgresql.persistence.size }}
    {{- end }}
  {{- end }}
{{- end }}
