{{- $builtinMariaDB := .Values.database.mariadb.enabled }}
{{- $builtinMySQL := .Values.database.mysql.enabled }}
{{- $builtinPostgreSQL := .Values.database.postgresql.enabled }}
{{- if or $builtinMariaDB $builtinMySQL $builtinPostgreSQL }}
{{- if or (and $builtinMariaDB (not .Values.database.mariadb.auth.existingSecret)) (and $builtinMySQL (not .Values.database.mysql.auth.existingSecret)) (and $builtinPostgreSQL (not .Values.database.postgresql.auth.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "speedtest-tracker.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "speedtest-tracker.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  {{- if $builtinMariaDB }}
  {{ .Values.database.mariadb.auth.passwordKey }}: {{ required "database.mariadb.auth.password or database.mariadb.auth.existingSecret is required" .Values.database.mariadb.auth.password | b64enc | quote }}
  {{- if .Values.database.mariadb.auth.rootPassword }}
  {{ default "db-root-password" .Values.database.mariadb.auth.rootPasswordKey }}: {{ .Values.database.mariadb.auth.rootPassword | b64enc | quote }}
  {{- end }}
  {{- else if $builtinMySQL }}
  {{ .Values.database.mysql.auth.passwordKey }}: {{ required "database.mysql.auth.password or database.mysql.auth.existingSecret is required" .Values.database.mysql.auth.password | b64enc | quote }}
  {{- if .Values.database.mysql.auth.rootPassword }}
  {{ default "db-root-password" .Values.database.mysql.auth.rootPasswordKey }}: {{ .Values.database.mysql.auth.rootPassword | b64enc | quote }}
  {{- end }}
  {{- else if $builtinPostgreSQL }}
  {{ .Values.database.postgresql.auth.passwordKey }}: {{ required "database.postgresql.auth.password or database.postgresql.auth.existingSecret is required" .Values.database.postgresql.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
