{{- if and (not .Values.speedtestTracker.secrets.existingSecret) .Values.speedtestTracker.secrets.inline -}}
{{- $hasInlineSecrets := false -}}
{{- range $key, $value := .Values.speedtestTracker.secrets.inline -}}
{{- if $value -}}
{{- $hasInlineSecrets = true -}}
{{- end -}}
{{- end -}}
{{- if $hasInlineSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "speedtest-tracker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "speedtest-tracker.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.speedtestTracker.secrets.inline }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
