apiVersion: v2
name: scrutiny
description: Scrutiny - Hard drive S.M.A.R.T monitoring via SSH (TrueNAS compatible)
type: application

# Chart version (increment when you change templates/values)
version: 0.1.0

# App version (Scrutiny version you’re targeting)
appVersion: "v0.9.2-web"

# Optional but good practice
keywords:
  - scrutiny
  - smart
  - monitoring
  - disks
  - truenas

home: https://github.com/AnalogJ/scrutiny

sources:
  - https://github.com/AnalogJ/scrutiny

maintainers:
  - name: harish2k01
