apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrent-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qbittorrent-exporter.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "qbittorrent-exporter.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
