apiVersion: v2
name: tor-proxy
description: Deploys a Tor SOCKS proxy on Kubernetes
type: application
icon: https://raw.githubusercontent.com/selfhst/icons/main/png/tor.png
version: 0.1.0
appVersion: "latest"
home: https://github.com/peterdavehello/tor-socks-proxy
sources:
  - https://github.com/peterdavehello/tor-socks-proxy
keywords:
  - tor
  - socks
  - proxy
  - privacy
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/images: |
    - name: tor-proxy
      image: peterdavehello/tor-socks-proxy:latest
maintainers:
  - name: harish2k01
