{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghost.mysqlServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "ghost.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
{{- end }}
