{{- if .Values.secretEnv.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $value := .Values.secretEnv.values }}
  {{- if ne (toString $value) "" }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
