{{- if .Values.token.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "cloudflared.tokenSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
    {{- with .Values.token.sealedSecret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.token.sealedSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  encryptedData:
    {{- required "token.sealedSecret.encryptedData is required when token.sealedSecret.enabled=true" .Values.token.sealedSecret.encryptedData | toYaml | nindent 4 }}
  template:
    metadata:
      name: {{ include "cloudflared.tokenSecretName" . }}
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "cloudflared.labels" . | nindent 8 }}
    type: Opaque
{{- end }}
