name: Lint Charts

on:
  pull_request:
    paths:
      - charts/**
      - .github/workflows/lint.yaml
  push:
    branches:
      - main
    paths:
      - charts/**
      - .github/workflows/lint.yaml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Lint charts
        run: helm lint charts/*
