{{- if and .Values.database.external.enabled (not .Values.database.external.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "umami.fullname" . }}-db-external
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "umami.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  {{ .Values.database.external.databaseUrlKey }}: {{ required "database.external.url or database.external.existingSecret is required when database.external.enabled=true" .Values.database.external.url | b64enc | quote }}
{{- end }}
