{{- if .Values.database.postgresql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "umami.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "umami.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  clusterIP: None
  selector:
    {{- include "umami.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
  ports:
    - port: {{ .Values.database.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
{{- end }}
