{{- if not .Values.umami.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "umami.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "umami.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.umami.secrets.appSecretKey }}: {{ required "umami.secrets.inline.APP_SECRET or umami.secrets.existingSecret is required" .Values.umami.secrets.inline.APP_SECRET | b64enc | quote }}
{{- end }}
